# Increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric properties — see https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod properties
version=1.0.0
group=com.aaravsingh.rubymod

# Dependencies
fabric_api_version=0.92.12+1.20.1
